# Generated by Django 5.2.7 on 2025-11-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_runner_description_remove_runner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
