# Generated by Django 5.2.7 on 2025-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_runner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='runners/'),
        ),
    ]
