# Generated by Django 5.2.7 on 2025-11-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_runner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='is_quiz_runner',
            field=models.BooleanField(default=False),
        ),
    ]
