# Generated by Django 5.2.7 on 2025-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_runner_is_quiz_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='quiz_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
