# Generated by Django 5.2.7 on 2025-11-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_quiz_answer_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
