# Generated by Django 5.2.7 on 2025-11-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_content_story_text_alter_story_user_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='username',
        ),
    ]
