# Generated by Django 5.2.7 on 2025-11-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_story_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='username',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
