# Generated by Django 5.2.7 on 2025-11-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_timelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
