# Generated by Django 5.2.7 on 2025-11-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_timelinereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinereference',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
