# Generated by Django 5.2.7 on 2025-12-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_timelinereference_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=20)),
                ('injury_history', models.CharField(max_length=10)),
                ('desired_mileage', models.IntegerField()),
                ('calculated_start', models.IntegerField()),
                ('calculated_jump', models.IntegerField()),
                ('calculated_weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
