# Generated by Django 5.2.7 on 2025-12-02 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mileageresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mileageresult',
            old_name='age_group',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='mileageresult',
            old_name='injury_history',
            new_name='injury',
        ),
        migrations.RenameField(
            model_name='mileageresult',
            old_name='calculated_jump',
            new_name='jump',
        ),
        migrations.RenameField(
            model_name='mileageresult',
            old_name='calculated_start',
            new_name='start_mileage',
        ),
        migrations.RenameField(
            model_name='mileageresult',
            old_name='calculated_weeks',
            new_name='weeks',
        ),
        migrations.RemoveField(
            model_name='mileageresult',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mileageresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
